version: '3.9'
services:
  controlflask:
    build: 
      context: ./flask-control
      args:
          model: $MODEL
          data: $DATA
          pipeline: $PIPELINE
    networks:
      - network1
    ports:
      - "5001:8082"
  experimentflask:
    build:
      context: ./flask-experiment
      args:
          female_model: $FEMALE_MODEL
          female_data: $FEMALE_DATA
          male_model: $MALE_MODEL
          male_data: $MALE_DATA
          pipeline: $PIPELINE
    networks:
      - network1
    ports:
      - "5002:8082"
  nginx:
    build: ./nginx
    networks:
      - network1
    ports:
      - "8082:80"
    depends_on:
      - controlflask
      - experimentflask
networks:
  network1:
    name: recommender
    external: true