version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    network_mode: host

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeexporter
    expose:
      - 9100
    network_mode: host

  grafana:
    image: grafana/grafana
    container_name: grafana
    expose:
      - 3000
    network_mode: host
    depends_on:
      - prometheus
